name: Danger
on:
  pull_request:
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: f-meloni/danger-swift-swiftlint-action@1.3.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}